fix pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,7 +9,6 @@ on:
 
 # ✅ Global Environment Variables
 env:
-  BUILD_NUMBER: ${{ github.run_number }}  # Unique build number for the pipeline run
   IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:${{ github.run_number }}
   BACKEND_URL: "https://api.30.lebondeveloppeur.net"  # Health check endpoint of the backend API 
   PORT: 3001  # Define a configurable port.
@@ -29,7 +28,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: '20'
 
       - name: Install dependencies
         run: npm install
@@ -70,34 +69,24 @@ jobs:
           username: ${{ secrets.VPS_USERNAME }}
           password: ${{ secrets.VPS_PASSWORD }}
           script: |
-            # Create Docker network if it doesn't exist
-            sudo docker network inspect backend-api-net || sudo docker network create backend-api-net
 
-            # Backup current image if running
-            if sudo docker ps -a --format '{{.Names}}' | grep -q 'backend-api'; then
-              current_image=$(sudo docker inspect backend-api --format='{{.Config.Image}}')
-              echo "Tagging current image ($current_image) as backup"
-              sudo docker tag $current_image backend-api:backup
-            fi
+              # Pull the latest Docker image
+              sudo docker pull ${{ env.IMAGE_NAME }}
+              
+              # Remove the old container if it exists
+              sudo docker rm -f backend-api || echo "No existing container to remove"
 
-            # Pull the latest Docker image
-            sudo docker pull ${{ env.IMAGE_NAME }}
-
-            # Remove the old container if it exists
-            sudo docker ps -q --filter name=backend-api | grep -q . && sudo docker rm -f backend-api || echo "No existing container to remove"
-
-            # Run the new container with environment variables
-            sudo docker run -d \
+              # Run the new container with environment variables
+              sudo docker run -d \
               --name backend-api \
               --network backend-api-net \
-              -p ${{ env.PORT }}:${{ env.PORT }} \
-              -e NODE_ENV=production \
+              -p 3001:3001 \
               -e MONGO_URI=${{ secrets.MONGO_URI }} \
               --restart=always \
               ${{ env.IMAGE_NAME }}
 
-            # Shows running containers
-            sudo docker ps
+              # Shows running containers
+              sudo docker ps
 
-            # Clean up unused images.
-            #sudo docker image prune -f  
+              # Clean up unused images
+              sudo docker image prune -f
